# Generated by Django 2.2.17 on 2021-06-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='slug',
            new_name='url_id',
        ),
    ]
